on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
      - name: checkout
        uses: actions/checkout@develop # 将代码拷贝到虚机中

      - name: Build and Deploy
        uses: lixiaoming-bit/vue-area-select@develop
        env:
          ACCESS_TOKEN: ${{ secrets.8105c1335adf02e6323daaf347b7c21a5cd8560b }} # 使用刚新建的secret
          BASE_BRANCH: develop
          BRANCH: gh-pages # 存放产物的分支名称
          FOLDER: dist # 存放build后产物的目录
          BUILD_SCRIPT: npm install && npm run build # 执行的命令
