on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
      - name: checkout
        uses: actions/checkout@master # 将代码拷贝到虚机中

      - name: Build and Deploy
        uses: lixiaoming-bit/vue-area-select@master
        env:
          ACCESS_TOKEN: ${{ secrets.vue-area-select }} # 使用刚新建的secret
          BASE_BRANCH: master
          BRANCH: gh-pages # 存放产物的分支名称
          FOLDER: dist # 存放build后产物的目录
          BUILD_SCRIPT: npm install && npm run build # 执行的命令
